services:
  cs130mp2jaymetinio:
    image: cs130mp2jaymetinio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 5005:5005
